#!/bin/bash

set -e

function quote_args {
  local QUOTED_ARGS=""
  while [[ $# -gt 0 ]]; do
    QUOTED_ARGS="${QUOTED_ARGS} $(printf "%q" "$1")"
    shift
  done
  echo "${QUOTED_ARGS}"
}

function main {
    local PROJECT_ROOT
    PROJECT_ROOT=$(realpath "$(dirname "$0")/../")

    eval "$(make -C "${PROJECT_ROOT}" -s docker-compose-env)"
    if [[ -z "${_CONTROL_CMD}" ]]; then
        echo "Error: undefined _CONTROL_CMD variable!" 1>&2
        return 1
    fi
    eval "${_CONTROL_CMD}" "$(quote_args "$@")"
}

main "$@"
