

###############################################################################
## Binaries
###############################################################################
DOCKER_BIN = docker
DOCKER_COMPOSE_BIN = docker-compose
DOCKER_COMPOSE_CMD = $(DOCKER_COMPOSE_ENV) $(DOCKER_COMPOSE_BIN) -p $(PROJECT_NAME) -f $(DOCKER_COMPOSE_FILES)
NVM_EXEC_BIN = $(DEVTOOLS_DIR)/nvm-exec.sh
NVM_EXEC_OPTIONS =
NVM_EXEC_CMD = $(NVM_EXEC_BIN) $(NVM_EXEC_OPTIONS)
YARN_CMD = $(NVM_EXEC_CMD) -- yarn
NPX_CMD = $(NVM_EXEC_CMD) -- npx
ANAKEEN_CLI_CMD = $(NPX_CMD) @anakeen/anakeen-cli
CHECK_VERSION_CMD = $(NVM_EXEC_CMD) $(DEVTOOLS_DIR)/ci/check/checkVersionNpmApp.js

###############################################################################
## Docker
###############################################################################
CONTAINER_PHP = web

DOCKER_DIR = $(DEVTOOLS_DIR)/docker
DOCKER_COMPOSE_UID = $$(id -u)
DOCKER_COMPOSE_GID = $$(id -g)
DOCKER_COMPOSE_ENV = COMPOSE_UID=$(DOCKER_COMPOSE_UID) COMPOSE_GID=$(DOCKER_COMPOSE_GID)
DOCKER_COMPOSE_ENV += PROJECT_HTTP_PORT=$(PROJECT_HTTP_PORT) PROJECT_PSQL_PORT=$(PROJECT_PSQL_PORT) PROJECT_MAIL_PORT=$(PROJECT_MAIL_PORT)
DOCKER_COMPOSE_ENV += PROJECT_PHP_VERSION=$(PROJECT_PHP_VERSION) PROJECT_POSTGRES_VERSION=$(PROJECT_POSTGRES_VERSION)
DOCKER_COMPOSE_UP_OPTIONS =
DOCKER_COMPOSE_DOWN_OPTIONS =
DOCKER_COMPOSE_SERVICES = web postgres
DOCKER_COMPOSE_SERVICES_WAIT_LIST = postgres:5432 web:80
DOCKER_COMPOSE_BASE_FILE = $(DOCKER_DIR)/docker-compose.yml
DOCKER_COMPOSE_OVERRIDES =
DOCKER_COMPOSE_FILES = $(DOCKER_COMPOSE_BASE_FILE) $(DOCKER_COMPOSE_OVERRIDES)

DOCKER_INTERNAL_SHARE_PATH = /tmp/share

DOCKER_INTERNAL_WEBROOT_BASE = /var/www/html/anakeen
DOCKER_INTERNAL_WEBROOT_CONTROL_DIR_PATH = $(DOCKER_INTERNAL_WEBROOT_BASE)/control
DOCKER_INTERNAL_WEBROOT_CONTEXT_PATH = $(DOCKER_INTERNAL_WEBROOT_BASE)/platform
DOCKER_INTERNAL_WEBROOT_VAULTS_PATH = $(DOCKER_INTERNAL_WEBROOT_BASE)/vaults
DOCKER_INTERNAL_WEBROOT_REPO_PATH = $(DOCKER_INTERNAL_WEBROOT_BASE)/repo
DOCKER_INTERNAL_WEBROOT_CERTS_PATH = $(DOCKER_INTERNAL_WEBROOT_BASE)/certs
DOCKER_INTERNAL_WEBROOT_SNAPSHOTS_PATH = $(DOCKER_INTERNAL_SHARE_PATH)/snapshots
DOCKER_INTERNAL_WEBROOT_CRONTABS_PATH = /var/spool/cron/crontabs
DOCKER_INTERNAL_POSTGRES_DATA_PATH = /var/lib/postgresql/data

###############################################################################
## Volumes
###############################################################################

VOLUMES_DIR = $(DOCKER_DIR)/Volumes
VOLUMES_PRIVATE_DIR = $(VOLUMES_DIR)/_private

VOLUMES_POSTGRES_DATA = $(VOLUMES_PRIVATE_DIR)/postgres/$(DOCKER_INTERNAL_POSTGRES_DATA_PATH)
VOLUMES_POSTGRES_SHARE = $(VOLUMES_PRIVATE_DIR)/postgres/$(DOCKER_INTERNAL_SHARE_PATH)

VOLUMES_WEBROOT_BASE = $(VOLUMES_PRIVATE_DIR)/webroot/$(DOCKER_INTERNAL_WEBROOT_BASE)
VOLUMES_WEBROOT_CONTEXT = $(VOLUMES_PRIVATE_DIR)/webroot/$(DOCKER_INTERNAL_WEBROOT_CONTEXT_PATH)
VOLUMES_WEBROOT_VAULTS = $(VOLUMES_PRIVATE_DIR)/webroot/$(DOCKER_INTERNAL_WEBROOT_VAULTS_PATH)
VOLUMES_WEBROOT_REPO = $(BUILD_DIR)
VOLUMES_WEBROOT_CERTS = $(VOLUMES_PRIVATE_DIR)/webroot/$(DOCKER_INTERNAL_WEBROOT_CERTS_PATH)
VOLUMES_WEBROOT_CONTROL = $(VOLUMES_PRIVATE_DIR)/webroot/$(DOCKER_INTERNAL_WEBROOT_CONTROL_DIR_PATH)
VOLUMES_WEBROOT_CONTROL_CONF = $(VOLUMES_WEBROOT_CONTROL)/conf
VOLUMES_WEBROOT_CRONTABS = $(VOLUMES_PRIVATE_DIR)/webroot/$(DOCKER_INTERNAL_WEBROOT_CRONTABS_PATH)
VOLUMES_WEBROOT_SHARE = $(VOLUMES_PRIVATE_DIR)/webroot/$(DOCKER_INTERNAL_SHARE_PATH)
VOLUMES_WEBROOT_SNAPSHOT_DIR = $(VOLUMES_PRIVATE_DIR)/webroot/$(DOCKER_INTERNAL_WEBROOT_SNAPSHOTS_PATH)

VOLUMES_TE_SHARE = $(VOLUMES_PRIVATE_DIR)/transformation-server/$(DOCKER_INTERNAL_SHARE_PATH)

VOLUMES_PRIVATE = $(VOLUMES_POSTGRES_DATA)
VOLUMES_PRIVATE += $(VOLUMES_POSTGRES_SHARE)
VOLUMES_PRIVATE += $(VOLUMES_WEBROOT_CONTEXT)
VOLUMES_PRIVATE += $(VOLUMES_WEBROOT_VAULTS)
VOLUMES_PRIVATE += $(VOLUMES_WEBROOT_REPO)
VOLUMES_PRIVATE += $(VOLUMES_WEBROOT_CERTS)
VOLUMES_PRIVATE += $(VOLUMES_WEBROOT_CONTROL)
VOLUMES_PRIVATE += $(VOLUMES_WEBROOT_CRONTABS)
VOLUMES_PRIVATE += $(VOLUMES_WEBROOT_SNAPSHOT_DIR)
VOLUMES_PRIVATE += $(VOLUMES_TE_SHARE)

###############################################################################
## Control
###############################################################################
CONTEXT_NAME = platform
CONTEXT_PASSWORD = anakeen
LOCAL_REPO_NAME = anakeen-platform-4

###############################################################################
## default values
###############################################################################

PROJECT_POSTGRES_VERSION = 11.6-1
PROJECT_PHP_VERSION = 7.3-1
PROJECT_PSQL_PORT = 54321
PROJECT_HTTP_PORT = 8080
PROJECT_DEVSERVER_PORT = 8001
PROJECT_MAIL_PORT = 8081

DEVTOOLS_DIR = .devtool
BUILD_DIR = build

WAIT_FOR_IT_TIMEOUT = 15

CORE_URLINDEX = http://localhost:$(PROJECT_HTTP_PORT)/

SSL_SERVER_NAMES = localhost 127.0.0.1 ::1 web

###############################################################################
## colors
###############################################################################
PRINT_COLOR = printf
COLOR_SUCCESS = \033[1;32m
COLOR_DEBUG = \033[36m
COLOR_HINT = \033[33m
COLOR_WARNING = \033[31m
COLOR_RESET = \033[0m

-include .devtool/Makefile.addons.mk
