#!/usr/bin/env php
<?php

/**
 * Initialize core application
 *
 * @author Anakeen
 */
/**
 */
require __DIR__ . "/../vendor/Anakeen/WHAT/Lib.Prefix.php";
require __DIR__ . '/../vendor/Anakeen/autoload.php';


$routeConfig = \Anakeen\Router\RouterLib::getRouterConfig();
$apps = $routeConfig->getApps();

$coreApp = $apps["CORE"];
$coreApp->addApplication(false);