#!/usr/bin/env php
<?php

/**
 * Initialize core application
 *
 * @author Anakeen
 */
/**
 */
include_once (__DIR__."/../vendor/Anakeen/WHAT/Lib.Prefix.php");
require_once('WHAT/autoload.php');


$routeConfig = \Anakeen\Router\RouterLib::getRouterConfig();
$apps=$routeConfig->getApps();

$coreApp=$apps["CORE"];
$coreApp->addApplication(false);