#!/bin/bash

mod_deflate=`"$WIFF_ROOT"/wiff --getValue=mod_deflate`


prefix="$WIFF_CONTEXT_ROOT"/WHAT/Lib.Prefix.php
corepost="$WIFF_CONTEXT_ROOT"/vendor/Anakeen/CORE_init



if [ ! -x "$corepost" ]; then
    echo "file '$corepost' not found or not executable" >&2
    exit 1
fi
# initialize configuration files

. "$WIFF_CONTEXT_ROOT/libutil.sh"

(
    set -e
    "$WIFF_CONTEXT_ROOT"/programs/core_accessUpdate
    
)
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error regenerating files from templates."
    exit $RET
fi

if [ "$mod_deflate" = "yes" ]; then
    cat <<EOF >> "$WIFF_CONTEXT_ROOT/public/.htaccess"

<IfModule mod_deflate.c>
	SetOutputFilter DEFLATE
</IfModule>

EOF
else
    cat <<EOF >> "$WIFF_CONTEXT_ROOT/public/.htaccess"

#<IfModule mod_deflate.c>
#	SetOutputFilter DEFLATE
#</IfModule>

EOF
fi

export wpub=$WIFF_CONTEXT_ROOT # same as `wiff --getValue=rootdirectory`
. "$WIFF_CONTEXT_ROOT"/programs/core_environment

"$corepost" I 
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error: '$corepost I' returned with exit code '$RET'"
    exit $RET
fi

"$corepost" U
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error: '$corepost U' returned with exit code '$RET'"
    exit $RET;
fi

exit 0
