#!/usr/bin/env php
<?php
/*
 * @author Anakeen
 * @package FDL
*/

$WIFF_ROOT = getenv("WIFF_ROOT");
if ($WIFF_ROOT === false) {
    print "WIFF_ROOT environment variable is not set!\n";
    exit(1);
}

$WIFF_CONTEXT_ROOT = getenv("WIFF_CONTEXT_ROOT");
if ($WIFF_CONTEXT_ROOT === false) {
    print "WIFF_CONTEXT_ROOT environment variable not set!\n";
    exit(1);
}

set_include_path(get_include_path() . PATH_SEPARATOR . $WIFF_CONTEXT_ROOT . PATH_SEPARATOR . "$WIFF_ROOT/include");


require __DIR__ . '/../vendor/Anakeen/autoload.php';
require __DIR__ . '/../vendor/Anakeen/WHAT/Lib.Prefix.php';

include_once ('lib/Lib.Cli.php');

$admin_passwd = wiff_getParamValue('core_admin_passwd');
if ($admin_passwd == '') {
    print "Empty core_admin_passwd.";
    exit(1);
}


$user = new \Anakeen\Core\Account("", 1);
if (!is_object($user) || !$user->isAffected()) {
    print "Could not find user with id '1' (admin).";
    exit(1);
}

$user->computepass($admin_passwd, $user->password);
$err = $user->modify(true, '', true);
if ($err != '') {
    print sprintf("Modify returned with error: %s", $err);
    exit(1);
}

$err = $user->setSupervisorHtpasswd($admin_passwd);
if ($err != '') {
    print sprintf("Error setting password in 'supervisor': %s", $err);
    exit(1);
}

exit(0);
