#!/bin/bash

pgservice_core=`"$WIFF_ROOT/wiff" --getValue=core_db`
if [ -z "$pgservice_core" ]; then
    echo "Error: undefined or empty CORE_DB"
    exit 1
fi

PGSERVICE="$pgservice_core" psql -c "update doc set fallid = docfam.cfallid from docfam where docfam.id = doc.fromid and docfam.cfallid is not null and doc.fallid is null"
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error: SQL error executing 'resetAccess': $RET"
    exit $RET
fi

exit 0
