#!/usr/bin/env php
<?php
// application.php

$loader = require __DIR__ . '/vendor/autoload.php';
$loader->addPsr4('', realpath(__DIR__ . '/src/'));


$rootPath = realpath(__DIR__);
set_include_path(get_include_path() . PATH_SEPARATOR . $rootPath . DIRECTORY_SEPARATOR . 'include');
putenv('WIFF_ROOT=' . $rootPath);

\Control\Internal\System::sudoWww();

use Symfony\Component\Console\Application;

$application = new Application();
$application->setVersion(\Control\Internal\Context::getVersion());
$application->setName("Anakeen Control");

// ... register commands
$application->add(new \Control\Cli\CliInfo());
$application->add(new \Control\Cli\CliShow());
$application->add(new \Control\Cli\CliSearch());
$application->add(new \Control\Cli\CliStatus());
$application->add(new \Control\Cli\CliLog());
$application->add(new \Control\Cli\CliInit());
$application->add(new \Control\Cli\CliGet());
$application->add(new \Control\Cli\CliSet());
$application->add(new \Control\Cli\CliOutdated());
$application->add(new \Control\Cli\CliRegistry());
$application->add(new \Control\Cli\CliInstallModule());
$application->add(new \Control\Cli\CliUpdateModule());
$application->add(new \Control\Cli\CliRemoveModule());
$application->add(new \Control\Cli\CliDoJob());
$application->add(new \Control\Cli\CliRun());

$application->run();