#!/usr/bin/env bash

npm config set @anakeen:registry "${CIBUILD_INTEGRATION_ANAKEEN_NPM_REGISTRY}"
npx npm-cli-login -u ${CIBUILD_INTEGRATION_ANAKEEN_NPM_LOGIN} -p ${CIBUILD_INTEGRATION_ANAKEEN_NPM_PASSWORD} -e ${CIBUILD_ANAKEEN_NPM_EMAIL} -r ${CIBUILD_INTEGRATION_ANAKEEN_NPM_REGISTRY} -s "@anakeen"
yarn install