#!/bin/bash


if [ -z "$WIFF_CONTEXT_ROOT" ]; then
    echo "Error: undefined WIFF_CONTEXT_ROOT"
    exit 1
fi

cd "$WIFF_CONTEXT_ROOT";
cd lib/jquery;
rm -f ddui;
ln -sf 2.1.4 ddui;


cd "$WIFF_CONTEXT_ROOT";
cd lib/KendoUI/;
rm -f ddui;
ln -sf 2016.1.120 ddui;

exit 0;