export interface ISeTabs {
  privateScope: {
    createKendoComponents(),
    createKendoTabStrip(),
    createKendoOpenedTabsList(),
    sendGetRequest(url: string, config: any, loadingElement: any),
    resizeComponents(),
    setTabstripPagination(),
    initTabModel(),
    canUseLazyTab(),
    getLazyTabIndex(),
    configureSortable(),
    setAddTabButton(addable: Boolean),
    setCloseTabButton(tab: any, forceClose?: Boolean),
    loadLazyTabDocument(data: any),
    bindWelcomeTabEvents(newTab: any, index: number),
    bindLazyTabEvents(tabContent ?: any, index ?: number),
    getSEEventHandler(eventName: string),
    bindDocumentTabEvents(doc: any, tabIndex: number),
    onModelAddItem(event),
    onModelRemoveItem(event),
    onModelItemChange(event),
    onAddGenericTab(index: number),
    onAddWelcomeTab(index: number),
    onAddLazyTab(index: number),
    onAddDocumentTab(index: number),
    onAddTabClick(event),
    onCloseTabClick(event),
    onCreateDocumentClick(event, index: number),
    onTabstripSelect(event),
    onOpenedTabsListDataBound(event),
    onOpenedTabsListItemClick(event),
    onDocumentReady(event, position: number),
    onDocumentActionClick(event),
    onDocumentAfterSave(event, position: number),
    formatSE(config),
    configureCloseTab(t, newValue),
    configureSortable(newValue),
  }
}