#MAKEFILE dir
MK_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

##bin
YARN_BIN=yarn

app:
	$(YARN_BIN) build

app-autorelease:
	$(YARN_BIN) build

app-test:
app-all: app
deploy:
deploy-test:
deploy-all:
lint:
po:
stub:
checkXML: