require([
      "kendo.core",
      "kendo-culture-en",
      "kendo-culture-fr",
      "kendo.draganddrop",
      "kendo.popup",
      "kendo.notification",
      "kendo.menu",
      "kendo.window",
      "kendo.autocomplete",
      "kendo.numerictextbox",
      "kendo.calendar",
      "kendo.datepicker",
      "kendo.timepicker",
      "kendo.datetimepicker",
      "kendo.multiselect",
      "kendo.combobox",
      "kendo.dropdownlist",
      "kendo.color",
      "kendo.slider",
      "kendo.colorpicker",
      "kendo.tabstrip",
      "kendo.button",
      "kendo.listview",
      "kendo.pager",
      "kendo.splitter"
    ], function require_kendo()
    {
    }, function onError(err) {
      console.error(err);
    }
);
