<?php
/**
 * Created by PhpStorm.
 * User: aurelien
 * Date: 21/11/17
 * Time: 13:34
 */

namespace Anakeen\Sample\Routes;


use Dcp\HttpApi\V1\Crud\Crud;
use Dcp\HttpApi\V1\Crud\DocumentCollection;
use Dcp\Core\DocManager;

class DocumentsSearch extends DocumentCollection
{
    protected function prepareSearchDoc()
    {
        parent::prepareSearchDoc(); // TODO: Change the autogenerated stub
        $famIds = [];
        if (!empty($this->contentParameters['collections'])) {
            $famNames = explode(',', $this->contentParameters['collections']);
            $filter = 'fromid IN (%s)';
            foreach ($famNames as $key => $name) {
                $famIds[] = DocManager::getFamilyIdFromName($name);
            }
            $this->_searchDoc->addFilter($filter, implode(",", $famIds));
        }
        if (!empty($this->contentParameters['filter'])) {
            $this->_searchDoc->addFilter("title ~* '%s'", $this->contentParameters['filter']);
        }
    }
}