define(["jquery",
    "@progress/kendo-ui/js/kendo.core",
    "@progress/kendo-ui/js/kendo.popup",
    "@progress/kendo-ui/js/kendo.notification",
    "@progress/kendo-ui/js/kendo.menu",
    "@progress/kendo-ui/js/kendo.window",
    "@progress/kendo-ui/js/kendo.autocomplete",
    "@progress/kendo-ui/js/kendo.numerictextbox",
    "@progress/kendo-ui/js/kendo.calendar",
    "@progress/kendo-ui/js/kendo.datepicker",
    "@progress/kendo-ui/js/kendo.timepicker",
    "@progress/kendo-ui/js/kendo.datetimepicker",
    "@progress/kendo-ui/js/kendo.multiselect",
    "@progress/kendo-ui/js/kendo.combobox",
    "@progress/kendo-ui/js/kendo.dropdownlist",
    "@progress/kendo-ui/js/kendo.color",
    "@progress/kendo-ui/js/kendo.slider",
    "@progress/kendo-ui/js/kendo.colorpicker",
    "@progress/kendo-ui/js/kendo.splitter",
    "@progress/kendo-ui/js/kendo.sortable",
    "@progress/kendo-ui/js/kendo.tabstrip",
    "@progress/kendo-ui/js/kendo.pager",
    "@progress/kendo-ui/js/kendo.button",
    "@progress/kendo-ui/js/kendo.listview"
], function ($, kendo) {
    return kendo.jQuery;
});
