version: '3'

services:
  web:
    build:
      context: ./Images/apache-mod_php/
      args:
        ANK_RUN_UID: ${COMPOSE_UID}
        ANK_RUN_GID: ${COMPOSE_GID}
        PROJECT_PHP_VERSION: ${PROJECT_PHP_VERSION-7.3-1}
    sysctls:
      # Allows mapping of port 80 form unprivileged user COMPOSE_UID
      net.ipv4.ip_unprivileged_port_start: 0
    volumes:
      - './Volumes/_private/webroot/var/www/html/anakeen:/var/www/html/anakeen'
      - './Volumes/_private/webroot/var/spool/cron/crontabs/:/var/spool/cron/crontabs'
      - './Volumes/_private/webroot/tmp/share/:/tmp/share/'

      - "../../build/:/var/www/html/anakeen/repo"

      - './Volumes/php/usr/local/etc/php/conf.d/10-base.ini:/usr/local/etc/php/conf.d/10-base.ini'
    ports:
      - '${PROJECT_HTTP_PORT-8080}:80'
    networks:
      internal:
        aliases:
          - php

  postgres:
    user: ${COMPOSE_UID}:${COMPOSE_GID}
    build:
      context: ./Images/postgres/
      args:
        PROJECT_POSTGRES_VERSION: ${PROJECT_POSTGRES_VERSION-11.6-1}
    volumes:
      - './Volumes/_private/postgres/var/lib/postgresql/data:/var/lib/postgresql/data'
      - './Volumes/_private/postgres/tmp/share/:/tmp/share/'
    ports:
      - '${PROJECT_PSQL_PORT-54320}:5432'
    networks:
      internal:
        aliases:
          - db

  mkcert:
    image: registry.ap4.anakeen.com/ank-mkcert:1.0.0-1
    user: ${COMPOSE_UID}:${COMPOSE_GID}
    volumes:
      - './Volumes/_private/webroot/var/www/html/anakeen/certs:/caroot'

  wait-for-it:
    build:
      context: ./Images/wait-for-it/
    networks:
      - internal

networks:
  internal: {}
