version: '3'

services:
  php:
    build:
      context: ./Images/php/
      args:
        ANK_RUN_UID: ${COMPOSE_UID}
        ANK_RUN_GID: ${COMPOSE_GID}
        PROJECT_PHP_VERSION: ${PROJECT_PHP_VERSION-7.3}
    sysctls:
      # Allows mapping of port 80 form unprivileged user COMPOSE_UID
      net.ipv4.ip_unprivileged_port_start: 0
    volumes:
      - './Volumes/_private/php/var/www/html/anakeen:/var/www/html/anakeen'
      - './Volumes/_private/php/var/spool/cron/crontabs/:/var/spool/cron/crontabs'
      - './Volumes/_private/php/tmp/share/:/tmp/share/'

      - "../../build/:/var/www/html/anakeen/repo"

      - './Volumes/php/usr/local/etc/php/conf.d/10-base.ini:/usr/local/etc/php/conf.d/10-base.ini'
    links:
      - 'postgres:postgres'
      - 'mail:mail'
    ports:
      - '${PROJECT_HTTP_PORT-8080}:80'
    networks:
      - internal

  postgres:
    user: ${COMPOSE_UID}:${COMPOSE_GID}
    build:
      context: ./Images/postgres/
      args:
        PROJECT_POSTGRES_VERSION: ${PROJECT_POSTGRES_VERSION-11.6}
    volumes:
      - './Volumes/_private/postgres/var/lib/postgresql/data:/var/lib/postgresql/data'
      - './Volumes/_private/postgres/tmp/share/:/tmp/share/'
    ports:
      - '${PROJECT_PSQL_PORT-54320}:5432'
    networks:
      - internal

  wait-for-it:
    build:
      context: ./Images/wait-for-it/
    networks:
      - internal
    links:
      - 'postgres:postgres'
      - 'php:php'

  mail:
    image: mailhog/mailhog
    networks:
      - internal
    ports:
      - '${PROJECT_MAIL_PORT-8081}:8025'

networks:
  internal: {}
